### ISSUE TITLE
How to sve global point cloud as a PCD or other types?

### ISSUE THREAD

**Issue by haiyang2022** [ZikangYuan/sr_lio#1]
Some parameters in the YAML file look similar to fast-lio2(E.g “pcd_save_en”), but I don't see any use of these parameters in the source code. The point cloud cannot be saved even if pcd_save_en is set to true. After turning on the debug mode, the saved point cloud does not seem to be in the global coordinate system. How should I save the final point cloud? Thank you for your help!!

**Comment by ZikangYuan** [comment]
I am sorry that this project has not yet opened the code to store the global point cloud map, but I will implement it soon.  

The YAML file of this project was indeed written with reference to fast-lio2, and some unnecessary parameters to our system were forgotten to be deleted. Now I have updated the YAML files. Thanks for pointing out my mistake.

**Comment by haiyang2022** [comment]
Thanks for your work and help.
