### ISSUE TITLE
running on the newer collage dataset and NTU viral dataset

### ISSUE THREAD

**Issue by snakehaihai** [ZikangYuan/sr_lio#2]
Hi  
Have you benchmarked the performance of SR_LIO and fast-lio2 for the newer collage dataset and NTU viral dataset?

How does it perform with lower speed vehicles?

**Comment by ZikangYuan** [comment]
I'm sorry that we didn't test SR_LIO on the NTU dataset. But NCLT dataset is also the dataset with a lower speed Segway (around 1.5~2m/s). Both SR_LIO and fast-lio2 can achieve great performance on NCLT.
