### ISSUE TITLE
CMake Error----  include could not find load file:  FetchContent

### ISSUE THREAD

**Issue by Lifapin** [ZikangYuan/sr_lio#3]
Hello, CMake Error. How can I solve it？

CMake Error at sr_lio/CMakeLists.txt:19 (include):
  include could not find load file:

    FetchContent

CMake Error at sr_lio/CMakeLists.txt:21 (FetchContent_Declare):
  Unknown CMake command "FetchContent_Declare".

-- Configuring incomplete, errors occurred!
See also "/home/jason/SR-LIO/build/CMakeFiles/CMakeOutput.log".
See also "/home/jason/SR-LIO/build/CMakeFiles/CMakeError.log".
Makefile:1496: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed

**Comment by Lifapin** [comment]
Thank you for everything !
After I update cmake3.18 and set CMakeLists After the 
set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} - std=c++14 - O3")
 in txt, it can be compiled normally.

**Comment by ZikangYuan** [comment]
I'm glad your problem has been solved.
