### ISSUE TITLE
The difference between BA based and optimization based framework

### ISSUE THREAD

**Issue by chengwei0427** [ZikangYuan/sr_lio#6]
Hi, @ZikangYuan 

  Thanks for your nice work.

  But I'm confused about the classification in your paper (**part 2, LiDAR-Inertial Odometry**), BA based and optimization based framework? What's the difference between them?

  Looking forward to your reply.

**Comment by ZikangYuan** [comment]
There are three kinds of tightly coupled frameworks for fusing 3D LiDAR and IMU: iterative extend Kalman filter (iEKF) framework, BA optimization framework and graph optimization framework. The framework based on BA and graph optimization can be called optimization framework.

**Comment by chengwei0427** [comment]
Thans for your reply. But what is difference between BA optimization and graph optimization?

In my opinion, they are all optimization algo which minimized the residual with edge and node,like graph.

**Comment by ZikangYuan** [comment]
In my opinion, BA uses both IMU and LiDAR residuals to solve the state vector. Graph based framework firstly uses LiDAR residuals to obtain state vectors, which are set as nodes. Then the IMU pre-integration is set as edge to adjust node. In other words, the LiDAR residuals and the IMU residuals do not provide constraints at the same time.

**Comment by chengwei0427** [comment]
Thank you for your patient reply. My problem is solved, and I'll close the issue. Thanks again.
