### ISSUE TITLE
Drift when motion_compensation is  CONSTANT_VELOCITY

### ISSUE THREAD

**Issue by chengwei0427** [ZikangYuan/sr_lio#8]
Hi, Dr. Yuan @ZikangYuan 

Thanks for your nice work.

在测试sr_lio时，遇到了一个问题，烦请有空帮忙解答一下；

在求解方式为LIO模式下，
motion_compensation设置为CONTINUOUS时，程序运行为CT_POINT_TO_PLANE的残差和IMU残差优化求解；
motion_compensation设置为CONSTANT_VELOCITY时，程序运行为POINT_TO_PLANE的残差和IMU残差优化求解；

在不改变其他参数的情况下，运行NCLT和KAIST的测试数据，当motion_compensation设置为CONSTANT_VELOCITY时，激光里程计总是会出现漂移，不知道是否是我那里设置有误？

配置文件：
[yaml.zip](https://github.com/ZikangYuan/sr_lio/files/11438118/yaml.zip)

期待你的回复！

![2023-05-10 11-46-14屏幕截图](https://github.com/ZikangYuan/sr_lio/assets/20199999/a0ef321c-9c55-4fa6-b0da-d8394005ca32)
![2023-05-10 11-47-32屏幕截图](https://github.com/ZikangYuan/sr_lio/assets/20199999/121ef175-6e70-45d3-becf-dfe30adb3739)

**Comment by ZikangYuan** [comment]
您好，感谢您对我们工作的兴趣，接下来，我将分别回答您的问题。

① 这个问题其实和issue#5的问题是一样的，当时这个问题被提出来后，我们和提问者一起对代码进行了详细的排查，排除了工程层面的bug。但是很遗憾，目前为止我们还没有找到CONSTANT_VELOCITY轨迹漂移的原因，但就现象而言，SR-LIO目前确实只适用于CONTINUOUS，毕竟当时我们在设计这个系统的时候，确实也是基于CONTINUOUS来设计雷达部分的。

② 速度差异的问题我是这么理解的。对于变量位姿而言，它既能受到来自IMU的状态预测约束，也能收到来自LiDAR ICP的观测约束，但是对于速度来说，它并没有观测约束，仅仅只有一个IMU预积分约束来推使它满足相邻两个时刻位姿间的相对关系，因此，速度这个状态量的值很大程度上是由位姿的值来间接决定的。这就是为什么速度会出现跳变或者异常等不准确现象的原因，也是为什么我们要设计LIW-OAM来引入轮速计为速度状态量提供观测的原因。另外，VIO系统中速度状态量的异常现象在BA框架尤为明显，如果您使用EKF框架，由于滤波框架会兼顾不同时刻状态量之间的平滑性，速度的跳变问题会有所缓解。

③ 建议您适当调整一下以下参数：
BA优化时IMU残差项和雷达残差项的权重(其中，IMU残差项的权重由imu_parameter的四个参数决定)
参与计算的ICP残差项的数目(min_num_residuals和max_num_residuals)
迭代优化次数(num_iters_icp和ls_max_num_iters)
根据我们的测试，这几个参数对系统精度的影响较大。

希望我的回答对您有帮助。

**Comment by ZikangYuan** [comment]
您好，感谢您对我们工作的兴趣。您的这个问题其实和issue#5的问题是一样的，当时这个问题被提出来后，我们和提问者一起对代码进行了详细的排查，排除了工程层面的bug。但是很遗憾，目前为止我们还没有找到CONSTANT_VELOCITY轨迹漂移的原因，但就现象而言，SR-LIO目前确实只适用于CONTINUOUS，毕竟当时我们在设计这个系统的时候，确实也是基于CONTINUOUS来设计雷达部分的。

**Comment by ZikangYuan** [comment]
代码已更新，CONSTANT_VELOCITY+POINT_TO_PLANE模式已能正常运行，感谢您提供的解决方案。
