### ISSUE TITLE
Running Error

### ISSUE THREAD

**Issue by dxdydz3dt** [ZikangYuan/sr_lio#9]
ERROR: cannot launch node of type [velodyne_pointcloud/cloud_node]: Cannot locate node of type [cloud_node] in package [velodyne_pointcloud]. Make sure file exists in package path and permission is set to executable (chmod +x)

**Comment by ZikangYuan** [comment]
I guess you used ubuntu 20.04, and the dataset you tested is utbm. We are sorry that the utbm launch file we provide is not support for ubuntu 20.04.

**Comment by dxdydz3dt** [comment]
Hi I using the Kaist Dataset Urban 17. 
Topics are published properly but I am getting this error.
How to solve it.
Bag details are follows:
path:        merged.bag
version:     2.0
duration:    20:05s (1205s)
start:       Apr 20 2018 09:53:20.67 (1524210800.67)
end:         Apr 20 2018 10:13:25.98 (1524212005.98)
size:        12.6 GB
messages:    2090771
compression: none [13066/13066 chunks]
types:       irp_sen_msgs/LaserScanArray [590075c3653e9b2cc1c75018fcbeedde]
             irp_sen_msgs/altimeter      [e6c99c37e6f9fe98e071d524cc164e65]
             irp_sen_msgs/encoder        [360abb290fcf41163977621351ecd430]
             irp_sen_msgs/fog_3axis      [2f13bb2da647a41df38407a7a8adc90a]
             irp_sen_msgs/imu            [97cd0887761aab329eff97e8b6aab17e]
             sensor_msgs/Imu             [6a62c6daae103f4ff57a132d6f95cec2]
             sensor_msgs/JointState      [3066dcd76a6cfaef579bd0f34173e9fd]
             sensor_msgs/MagneticField   [2f3b0b43eed0c9501de0fa3ff89a45aa]
             sensor_msgs/NavSatFix       [2d3a8cd499b9b4a0249fb98fd05cfa48]
             sensor_msgs/PointCloud2     [1158d486dd51d683ce2f1be655c3c181]
topics:      /altimeter_data          12054 msgs    : irp_sen_msgs/altimeter     
             /dsp1760_data          1205374 msgs    : irp_sen_msgs/fog_3axis     
             /encoder_count          120534 msgs    : irp_sen_msgs/encoder       
             /gps/fix                  6055 msgs    : sensor_msgs/NavSatFix      
             /imu/data_raw           120540 msgs    : sensor_msgs/Imu            
             /imu/mag                120540 msgs    : sensor_msgs/MagneticField  
             /joint_states           120533 msgs    : sensor_msgs/JointState     
             /lms511_back/scan       120350 msgs    : irp_sen_msgs/LaserScanArray
             /lms511_middle/scan     120350 msgs    : irp_sen_msgs/LaserScanArray
             /ns1/velodyne_points     11951 msgs    : sensor_msgs/PointCloud2    
             /ns2/velodyne_points     11950 msgs    : sensor_msgs/PointCloud2    
             /xsens_imu_data         120540 msgs    : irp_sen_msgs/imu
Error while running. 
odom_enble : true
Failed to find match for field 'time'.
Failed to find match for field 'ring'.

Details
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://malik:33379/

SUMMARY
========

PARAMETERS
 * /common/gravity_acc: [0.0, 0.0, 9.80416]
 * /common/imu_topic: /imu/data_raw
 * /common/lidar_topic: /ns1/velodyne_points
 * /common/point_filter_num: 4
 * /common/sweep_cut_num: 1
 * /common/time_sync_en: False
 * /common/wheel_topic: /velocity
 * /debug_output: False
 * /extrinsic_parameter/extrinsic_R: [-0.515105, -0.70...
 * /extrinsic_parameter/extrinsic_R_odom: [1.0, 0.0, 1.0, 0...
 * /extrinsic_parameter/extrinsic_enable: False
 * /extrinsic_parameter/extrinsic_t: [0.58743, -0.0292...
 * /extrinsic_parameter/extrinsic_t_odom: [0.0, 0.0, 0.0]
 * /icp_options/beta_constant_velocity: 1.0
 * /icp_options/beta_location_consistency: 1.0
 * /icp_options/beta_orientation_consistency: 1.0
 * /icp_options/beta_small_velocity: 0.0
 * /icp_options/beta_wheel_velocity: 1.0
 * /icp_options/debug_print: False
 * /icp_options/distance: CT_POINT_TO_PLANE
 * /icp_options/loss_function: HUBER
 * /icp_options/ls_max_num_iters: 5
 * /icp_options/ls_num_threads: 16
 * /icp_options/ls_sigma: 0.5
 * /icp_options/ls_tolerant_min_threshold: 0.05
 * /icp_options/max_dist_to_plane_ct_icp: 0.3
 * /icp_options/max_num_residuals: 600
 * /icp_options/max_number_neighbors: 20
 * /icp_options/min_num_residuals: 200
 * /icp_options/min_number_neighbors: 20
 * /icp_options/num_closest_neighbors: 1
 * /icp_options/num_iters_icp: 15
 * /icp_options/point_to_plane_with_distortion: True
 * /icp_options/size_voxel_map: 1.0
 * /icp_options/solver: LIW
 * /icp_options/threshold_orientation_norm: 0.1
 * /icp_options/threshold_translation_norm: 0.01
 * /icp_options/voxel_neighborhood: 1
 * /imu_parameter/acc_cov: 0.1
 * /imu_parameter/b_acc_cov: 0.0001
 * /imu_parameter/b_gyr_cov: 0.0001
 * /imu_parameter/gyr_cov: 0.1
 * /imu_parameter/time_diff_enable: True
 * /imu_parameter/vel_cov: 0.1
 * /lidar_parameter/N_SCANS: 16
 * /lidar_parameter/SCAN_RATE: 10
 * /lidar_parameter/blind: 2
 * /lidar_parameter/det_range: 100.0
 * /lidar_parameter/fov_degree: 180
 * /lidar_parameter/lidar_type: 2
 * /lidar_parameter/time_unit: 0
 * /odometry_options/distance_error_threshold: 100.0
 * /odometry_options/init_num_frames: 20
 * /odometry_options/initialization: INIT_IMU
 * /odometry_options/max_distance: 2000.0
 * /odometry_options/max_num_points_in_voxel: 20
 * /odometry_options/method_system_init: STATIC_INIT
 * /odometry_options/min_distance_points: 0.15
 * /odometry_options/motion_compensation: CONTINUOUS
 * /odometry_options/robust_registration: False
 * /odometry_options/sample_voxel_size: 1.5
 * /odometry_options/voxel_size: 0.5
 * /output_path: /home/malik/LIW-O...
 * /rosdistro: noetic
 * /rosversion: 1.16.0

NODES
  /
    lio_optimization (liw_oam/lio_optimization)
    rviz (rviz/rviz)

auto-starting new master
process[master]: started with pid [76494]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 1899eed2-1aa0-11ee-809d-c932c3084bcd
process[rosout-1]: started with pid [76507]
started core service [/rosout]
process[lio_optimization-2]: started with pid [76510]
process[rviz-3]: started with pid [76515]
[ INFO] [1688498541.739674905]: odom_enble:....................................
odom_enble : true
Failed to find match for field 'time'.
Failed to find match for field 'ring'.
Failed to find match for field 'time'.
Failed to find match for field 'ring'.
Failed to find match for field 'time'.
Failed to find match for field 'ring'.
Failed to find match for field 'time'.
Failed to find match for field 'ring'.
Failed to find match for field 'time'.
